Feature/MP-admin-Hall-Of-Fame
mugetsu0422/HCMUS-Alumni-Web pull request #28
Opened 2024-05-09 09:32 UTC by PhucJosehp

2024-05-13 11:00 UTC, mugetsu0422 requested changes

2024-05-13 11:00 UTC, mugetsu0422 commented on .hintrc
what is this

2024-05-13 11:00 UTC, mugetsu0422 commented on src/app/admin/hof/[id]/page.tsx
> +  // }
làm ko bật server hả ô

2024-05-13 11:00 UTC, mugetsu0422 commented on src/app/admin/hof/page.tsx
> +// }
xoá

2024-05-13 11:00 UTC, mugetsu0422 commented on src/app/admin/hof/create/page.tsx
chưa thêm cái input nhập vị trí/ nổi bật của ng đó hả ô

2024-05-13 11:00 UTC, mugetsu0422 commented on src/app/admin/hof/[id]/page.tsx
chưa thêm cái input nhập vị trí/ nổi bật của ng đó hả ô

2024-05-14 00:56 UTC, PhucJosehp commented on src/app/admin/hof/[id]/page.tsx
> +  // }
xin lại file data mới đi ông

2024-05-21 13:34 UTC, merged