Feature/mp profile
mugetsu0422/HCMUS-Alumni-Web pull request #38
Opened 2024-06-11 02:52 UTC by PhucJosehp

2024-06-12 12:58 UTC, mugetsu0422 requested changes
1. Thông tin cơ bản và liên hệ (Giới thiệu)
Chỉnh lại các input sau
- Khóa chỉ cho nhập số tối đa 4 số
- Khoa là select lấy từ FACULTIES bên constant
- MSSV chỉ cho nhập số tối đa 4 số
- Ngày sinh là date
- Giới tính là select cũng lấy từ constant
- Sđt chỉ cho nhập số
2. Công việc và học vấn ( Giới thiệu)
- Phần chỉnh sửa công việc ngày bắt đầu và kết thúc là date. Button còn là thêm
- Phần học vấn chưa có chỉnh sửa và thêm mới
3. Thành tựu nổi bật ( Giới thiệu)
- Chưa thấy chỉnh sửa

2024-06-16 17:42 UTC, mugetsu0422 requested changes
1. Thông tin cơ bản và liên hệ (Giới thiệu)
- Label khóa với khoa bị ngược r ô
- MSSV cho nhập 8 số, nhầm :( sr
2. Công việc và học vấn ( Giới thiệu)
- Button của chỉnh sửa là "Cập nhật" chứ ko phải "Thêm"

2024-06-23 10:16 UTC, mugetsu0422 requested changes
Tiêu đề của Dialog cover còn là "Chọn ảnh đại diện" thay vì "ảnh bìa"
Thiếu toast thông báo ko dc chọn file > 5 MB

2024-06-24 12:24 UTC, mugetsu0422 requested changes
chỉnh lại như t nhắn với b nha

2024-06-25 03:43 UTC, mugetsu0422 requested changes
Ở cái trang post-counsel b thêm cái tab bên trong nữa, chia ra làm bài viết và bình luận. UI này b bàn với nduy với tham khảo hình chụp UI reddit t có gửi trong group. Xong UI này đi r t phụ b gắn api để b làm tiếp UI tin nhắn

2024-06-25 03:43 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/page.tsx
> +      .get(`${process.env.NEXT_PUBLIC_SERVER_HOST}/counsel/${userId}`, {
```suggestion
      .get(`${process.env.NEXT_PUBLIC_SERVER_HOST}/counsel/users/${userId}`, {
```

2024-06-25 03:43 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/page.tsx
> +  useEffect(() => {
Thêm cái check userId trong cookies với userId trên params đi. Tại cái này private. 2 userId khác nhau thì redirect về activities. Cái tab cũng v lun, kt để hiển thị hay ko

2024-06-25 03:43 UTC, mugetsu0422 commented on src/app/ui/social-page/profile/profile-post-list-items.tsx
> +/* eslint-disable @next/next/no-img-element */
Thấy dùng chung post list item bên counsel dc mà nhỉ. Đâu cần tạo cái mới

2024-07-08 03:55 UTC, mugetsu0422 requested changes
cập nhật lại mấy cái toast trong catch
chỉ cập nhật cho api post và put, catch của api get thì chỉ cần `.catch(error => {})`

2024-07-08 03:55 UTC, mugetsu0422 commented on .hintrc
> +>>>>>>> c0c38b9d154d3966670b5f3bb650d247ffbb0839
resolve conflict kiểu gì v 😔
file này sao thấy b chỉnh miết lun

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/counsel-comments/page.tsx
> +  }
sao ko thấy fetch data v ô

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/counsel-comments/page.tsx
> +        console.log(comments)
```suggestion
```
xóa log

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/page.tsx
> +    }
sao ko fetch data 😔

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/counsel-posts/page.tsx
> +        console.log(posts)
```suggestion
```
xóa log

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/page.tsx
> +      )} */}
```suggestion
        {/* {totalPages > 1 && (
        <Pagination
          totalPages={totalPages}
          curPage={curPage}
          onNextPage={onNextPage}
          onPrevPage={onPrevPage}
        />
      )} */}
```
ko dùng phân trang thì xóa

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/page.tsx
> +  }
```suggestion
```
thấy ko dùng phân trang -> xóa
ko dùng phân trang thì dùng infinite loading

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/layout.tsx
> +        console.log(error)
```suggestion
```
xóa

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/layout.tsx
> +        toast.success('Avatar updated successfully')
```suggestion
        toast.success('Dùng tiếng việt')
```

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/layout.tsx
thông báo đó h dùng tiếng việt, r sao nay dùng tiếng anh v ô

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/layout.tsx
> +      })
trong catch thì ko dùng cái này
```suggestion
      .catch((error) => {
        toast.error(error.response?.data?.error?.message || 'Lỗi không xác định')
      })
```
sửa lại những cái toast nào b đã làm như v

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/(social-page)/profile/[id]/activities/layout.tsx
> +          {PROFILE_JOINED_EVENTS_TABS.map(({ label, url }) => (
kt xem ko phải chính bản thân ng dùng thì ko hiển thị tab tư vấn lun

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/constant.ts
> +export const PROFILE_JOINED_EVENTS_TABS = [
```suggestion
export const PROFILE_ACTIVITIES_TABS = [
```

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/constant.ts
> +    label: 'Tư vấn & cố vấn',
```suggestion
    label: 'Tư vấn',
```
đồng nhất với trên navbar

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/ui/social-page/navbar.tsx
chỉnh bên nav bar admin tương tự như v lun

2024-07-08 03:55 UTC, mugetsu0422 commented on src/app/ui/social-page/profile/ProfileWorksUI.tsx
> +        console.log(error)
```suggestion
```
xóa log, cập nhật lại những cái catch của b thành như phần trên t đã nói

2024-07-09 03:09 UTC, PhucJosehp commented on .hintrc
> +>>>>>>> c0c38b9d154d3966670b5f3bb650d247ffbb0839
nó cứ z á ko bk luôn

2024-07-22 05:19 UTC, mugetsu0422 requested changes
sao còn thấy xài z-index lung tung v, có chắc là dùng nó thì ko ảnh hưởng tới những thứ khác như navbar, thông báo trên navbar ko
r cái lỗi ko hiện thông báo navbar ở trang chủ social-page chưa thấy fix -> cũng là do dùng z-index bừa bãi, lung tung

2024-07-22 05:19 UTC, mugetsu0422 commented on src/app/ui/admin/common/navbar.tsx
> +    alert('ok')
```suggestion
```
alert chi v ô

2024-07-22 05:19 UTC, mugetsu0422 commented on package.json
r sao xóa mấy thư viện này v, đưa về như cũ

2024-07-22 05:51 UTC, PhucJosehp commented on src/app/ui/admin/common/navbar.tsx
> +    alert('ok')
cái này xóa lâu r mà ta

2024-07-22 05:51 UTC, PhucJosehp commented on package.json
có xóa j đâu ??

2024-07-22 05:57 UTC, mugetsu0422 commented on package.json
chứ mấy dòng màu đỏ đó ko xóa thì là gì, đưa về như cũ đi
thiếu thư viện là bị lỗi

2024-07-23 02:56 UTC, mugetsu0422 approved these changes

2024-07-23 02:56 UTC, merged