Update API for vote post
mugetsu0422/HCMUS-Alumni-Web pull request #43
Opened 2024-06-14 04:42 UTC by PhucJosehp

double check lại nha

2024-06-14 08:21 UTC, mugetsu0422 requested changes
Chưa chỉnh cho trang chi tiết và chỉnh sửa của post trong group nha ô

2024-06-14 08:21 UTC, mugetsu0422 commented on src/app/(social-page)/groups/[id]/posts/create/page.tsx
> +            `${process.env.NEXT_PUBLIC_SERVER_HOST}/groups/${id}/posts/images`,
```suggestion
            `${process.env.NEXT_PUBLIC_SERVER_HOST}/groups/${id}/posts/images`,
```
sai url, check lại

2024-06-14 09:24 UTC, PhucJosehp commented on src/app/(social-page)/groups/[id]/posts/create/page.tsx
> +            `${process.env.NEXT_PUBLIC_SERVER_HOST}/groups/${id}/posts/images`,
cái API file excel ghi z ông

2024-06-16 17:42 UTC, mugetsu0422 approved these changes

2024-06-16 17:43 UTC, merged