user friend UI
mugetsu0422/HCMUS-Alumni-Web pull request #44
Opened 2024-06-17 14:00 UTC by PhucJosehp

2024-06-18 12:17 UTC, mugetsu0422 requested changes

2024-06-18 12:17 UTC, mugetsu0422 commented on src/app/(social-page)/friends/friend-requests/page.tsx
`requests` thay vì `friend-requests`

2024-06-25 16:49 UTC, PhucJosehp commented
Bạn double check lại UI. Bạn ok thì tui quay clip gửi group check

2024-06-26 02:11 UTC, mugetsu0422 requested changes
đổi folder `messenger` thành `messages`

2024-06-27 17:06 UTC, mugetsu0422 requested changes
Chỉnh mấy cái t nhắn với b

2024-06-28 15:49 UTC, mugetsu0422 approved these changes

2024-06-28 15:54 UTC, merged