Fix UI pt1
mugetsu0422/HCMUS-Alumni-Web pull request #73
Opened 2024-08-04 14:00 UTC by PhucJosehp

2024-08-04 14:54 UTC, PhucJosehp commented
part 1: sửa theo những gì thầy kêu sửa trong buổi họp. Tiện sửa luôn những UI cần sửa ở bên web + mobile.

2024-08-04 17:03 UTC, mugetsu0422 requested changes
chỉnh lại như t nhắn

2024-08-06 03:24 UTC, mugetsu0422 requested changes
chỉnh lại như trong tin nhắn

2024-08-06 03:24 UTC, mugetsu0422 commented on src/app/ui/admin/verify-alumni/filter-for-pending.tsx
>    }, 500)
500 này là gì

2024-08-06 11:09 UTC, mugetsu0422 approved these changes

2024-08-06 11:09 UTC, merged